### ISSUE TITLE
Compatibility with Armor Statues

### ISSUE THREAD

**Issue by WimpieRatte** [Alan72104/ArmorStandShiftSwap#1]
Due to both mods using Shift + R-Click, it's not possible to use this with Armor Statues. (Same issue with the Carry-On mod, which allows moving the entire armor stand.)
Would be nice if we could rebind the armor swapping to a different shortcut key. (E.g: Pressing "O".)
Similar to the recent "Timeless and Classics Zero" mod, it would be nice if a text pops up to show which button can be pressed to swap the armor, like they have when looking at their workbench.

**Comment by Chris6ix** [comment]
The same issue is also happening with [Armor Poser](https://modrinth.com/mod/armor-poser). Having the ability to rebind the key ArmorStandShiftSwap uses would be nice.

**Comment by Alan72104** [comment]
Fixed in e86fe387e28e09f73f88f96ed01cb64f71ba4f2b

Keybind support added, I tried using architectury api since it needed custom packets, also to see if the api would provide a better armor stand interaction hook, turns out no it doens't lol
I'll keep the dependency since more people are going to download it too for other mods
